server:
  port: 8085

spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/train
    username: root
    password: "root"

#mybatis相关配置
mybatis:
  type-aliases-package: top.lbqaq.model,;top.lbqaq.dto
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    #开启自动驼峰转换
    map-underscore-to-camel-case: true